// This file is auto-generated by the updateMoleculeConstants script
// Do not edit directly

export const MOLECULE_BONDS: [number, number][] = [
  [0, 1], // Bond 1-2 (single)
  [0, 2], // Bond 1-3 (single)
  [0, 10], // Bond 1-11 (single)
  [0, 11], // Bond 1-12 (single)
  [1, 6], // Bond 2-7 (single)
  [1, 8], // Bond 2-9 (single)
  [1, 12], // Bond 2-13 (single)
  [2, 3], // Bond 3-4 (single)
  [2, 4], // Bond 3-5 (single)
  [2, 13], // Bond 3-14 (single)
  [3, 5], // Bond 4-6 (single)
  [3, 14], // Bond 4-15 (single)
  [3, 15], // Bond 4-16 (single)
  [4, 9], // Bond 5-10 (single)
  [4, 16], // Bond 5-17 (single)
  [4, 17], // Bond 5-18 (single)
  [5, 6], // Bond 6-7 (single)
  [5, 7], // Bond 6-8 (single)
  [5, 18], // Bond 6-19 (single)
  [6, 19], // Bond 7-20 (single)
  [6, 20], // Bond 7-21 (single)
  [7, 9], // Bond 8-10 (single)
  [7, 21], // Bond 8-22 (single)
  [7, 22], // Bond 8-23 (single)
  [8, 9], // Bond 9-10 (single)
  [8, 23], // Bond 9-24 (single)
  [8, 24], // Bond 9-25 (single)
  [9, 25], // Bond 10-26 (single)
];

export interface AtomPosition {
  x: number;
  y: number;
  z: number;
}

export const ATOM_POSITIONS: AtomPosition[] = [
  { x: -0.3705, y: 0.2545, z: 0.0049 },   // 0
  { x: -0.3652, y: -0.1348, z: 0.0028 },   // 1
  { x: -0.0053, y: 0.3893, z: 0.0021 },   // 2
  { x: 0.1830, y: 0.2603, z: 0.3175 },   // 3
  { x: 0.1769, y: 0.2637, z: -0.3182 },   // 4
  { x: 0.1883, y: -0.1290, z: 0.3154 },   // 5
  { x: -0.1769, y: -0.2637, z: 0.3182 },   // 6
  { x: 0.3705, y: -0.2545, z: -0.0049 },   // 7
  { x: -0.1830, y: -0.2603, z: -0.3175 },   // 8
  { x: 0.1822, y: -0.1255, z: -0.3203 },   // 9
  { x: -0.5047, y: 0.3464, z: -0.2198 },   // 10
  { x: -0.5003, y: 0.3440, z: 0.2331 },   // 11
  { x: -0.6254, y: -0.2308, z: 0.0047 },   // 12
  { x: -0.0090, y: 0.6666, z: 0.0037 },   // 13
  { x: 0.4432, y: 0.3563, z: 0.3156 },   // 14
  { x: 0.0532, y: 0.3497, z: 0.5457 },   // 15
  { x: 0.0428, y: 0.3556, z: -0.5429 },   // 16
  { x: 0.4371, y: 0.3597, z: -0.3201 },   // 17
  { x: 0.3224, y: -0.2208, z: 0.5401 },   // 18
  { x: -0.3068, y: -0.1743, z: 0.5463 },   // 19
  { x: -0.1732, y: -0.5410, z: 0.3167 },   // 20
  { x: 0.6307, y: -0.1585, z: -0.0069 },   // 21
  { x: 0.3743, y: -0.5318, z: -0.0064 },   // 22
  { x: -0.1793, y: -0.5376, z: -0.3191 },   // 23
  { x: -0.3172, y: -0.1684, z: -0.5422 },   // 24
  { x: 0.3120, y: -0.2150, z: -0.5485 },   // 25
];