// This file is auto-generated by the updateMoleculeConstants script
// Do not edit directly

export const MOLECULE_BONDS: [number, number][] = [
  [0, 1], // Bond 1-2 (single)
  [0, 2], // Bond 1-3 (double)
  [0, 3], // Bond 1-4 (single)
  [1, 6], // Bond 2-7 (single)
  [1, 7], // Bond 2-8 (double)
  [2, 4], // Bond 3-5 (single)
  [2, 5], // Bond 3-6 (single)
  [3, 12], // Bond 4-13 (single)
  [3, 13], // Bond 4-14 (single)
  [4, 8], // Bond 5-9 (single)
  [4, 9], // Bond 5-10 (single)
  [5, 12], // Bond 6-13 (double)
  [6, 8], // Bond 7-9 (single)
  [6, 10], // Bond 7-11 (single)
  [8, 11], // Bond 9-12 (double)
  [9, 14], // Bond 10-15 (single)
  [9, 15], // Bond 10-16 (single)
  [9, 16], // Bond 10-17 (single)
  [10, 17], // Bond 11-18 (single)
  [10, 18], // Bond 11-19 (single)
  [10, 19], // Bond 11-20 (single)
  [12, 20], // Bond 13-21 (single)
  [13, 21], // Bond 14-22 (single)
  [13, 22], // Bond 14-23 (single)
  [13, 23], // Bond 14-24 (single)
];

export interface AtomPosition {
  x: number;
  y: number;
  z: number;
}

export const ATOM_POSITIONS: AtomPosition[] = [
  { x: -0.1190, y: 0.0611, z: 0.0020 },   // 0
  { x: -0.1160, y: -0.1633, z: 0.0008 },   // 1
  { x: 0.0725, y: 0.1714, z: 0.0008 },   // 2
  { x: -0.2775, y: 0.2132, z: 0.0035 },   // 3
  { x: 0.2609, y: 0.0573, z: -0.0017 },   // 4
  { x: 0.0258, y: 0.3786, z: 0.0023 },   // 5
  { x: 0.0727, y: -0.2656, z: -0.0016 },   // 6
  { x: -0.2817, y: -0.2636, z: 0.0019 },   // 7
  { x: 0.2568, y: -0.1568, z: -0.0030 },   // 8
  { x: 0.4650, y: 0.1697, z: -0.0031 },   // 9
  { x: 0.0770, y: -0.4985, z: -0.0029 },   // 10
  { x: 0.4238, y: -0.2543, z: -0.0052 },   // 11
  { x: -0.1808, y: 0.4044, z: 0.0041 },   // 12
  { x: -0.5071, y: 0.1740, z: 0.0040 },   // 13
  { x: 0.5172, y: 0.1966, z: 0.1601 },   // 14
  { x: 0.5831, y: 0.0740, z: -0.0865 },   // 15
  { x: 0.4466, y: 0.3220, z: -0.0837 },   // 16
  { x: 0.0765, y: -0.5554, z: -0.1666 },   // 17
  { x: 0.2204, y: -0.5541, z: 0.0772 },   // 18
  { x: -0.0626, y: -0.5594, z: 0.0799 },   // 19
  { x: -0.2615, y: 0.5560, z: 0.0053 },   // 20
  { x: -0.5635, y: 0.1633, z: 0.1676 },   // 21
  { x: -0.5882, y: 0.3043, z: -0.0766 },   // 22
  { x: -0.5406, y: 0.0252, z: -0.0784 },   // 23
];