// This file is auto-generated by the updateMoleculeConstants script
// Do not edit directly

export const MOLECULE_BONDS: [number, number][] = [
  [0, 3], // Bond 1-4 (single)
  [0, 7], // Bond 1-8 (single)
  [1, 3], // Bond 2-4 (double)
  [2, 3], // Bond 3-4 (single)
  [2, 4], // Bond 3-5 (single)
  [2, 5], // Bond 3-6 (single)
  [2, 6], // Bond 3-7 (single)
];

export interface AtomPosition {
  x: number;
  y: number;
  z: number;
}

export const ATOM_POSITIONS: AtomPosition[] = [
  { x: -0.2311, y: 0.3672, z: -0.0000 },   // 0
  { x: -0.4275, y: -0.2650, z: -0.0000 },   // 1
  { x: 0.2562, y: -0.1093, z: -0.0000 },   // 2
  { x: -0.1693, y: -0.0216, z: 0.0002 },   // 3
  { x: 0.3905, y: 0.0094, z: -0.2619 },   // 4
  { x: 0.3914, y: 0.0125, z: 0.2600 },   // 5
  { x: 0.2987, y: -0.4240, z: 0.0019 },   // 6
  { x: -0.5088, y: 0.4308, z: -0.0002 },   // 7
];