// This file is auto-generated by the updateMoleculeConstants script
// Do not edit directly

export const MOLECULE_BONDS: [number, number][] = [
  [0, 1], // Bond 1-2 (single)
  [1, 2], // Bond 2-3 (single)
  [1, 3], // Bond 2-4 (single)
  [1, 4], // Bond 2-5 (single)
  [4, 5], // Bond 5-6 (single)
  [4, 6], // Bond 5-7 (single)
  [4, 7], // Bond 5-8 (single)
];

export interface AtomPosition {
  x: number;
  y: number;
  z: number;
}

export const ATOM_POSITIONS: AtomPosition[] = [
  { x: 0.1629, y: -0.5838, z: -0.2776 },   // 0
  { x: 0.1564, y: -0.1078, z: -0.2749 },   // 1
  { x: 0.6031, y: 0.0570, z: -0.2783 },   // 2
  { x: -0.0739, y: 0.0500, z: -0.6607 },   // 3
  { x: -0.1564, y: 0.1077, z: 0.2749 },   // 4
  { x: -0.1629, y: 0.5838, z: 0.2775 },   // 5
  { x: -0.6031, y: -0.0570, z: 0.2783 },   // 6
  { x: 0.0738, y: -0.0499, z: 0.6607 },   // 7
];