// This file is auto-generated by the updateMoleculeConstants script
// Do not edit directly

export const MOLECULE_BONDS: [number, number][] = [
  [1, 0], // Bond 2-1 (single)
  [0, 2], // Bond 1-3 (single)
  [3, 0], // Bond 4-1 (single)
  [0, 11], // Bond 1-12 (single)
  [2, 1], // Bond 3-2 (single)
  [3, 1], // Bond 4-2 (single)
  [1, 4], // Bond 2-5 (single)
  [5, 1], // Bond 6-2 (single)
  [6, 1], // Bond 7-2 (single)
  [7, 1], // Bond 8-2 (single)
  [8, 1], // Bond 9-2 (single)
  [1, 9], // Bond 2-10 (single)
  [1, 10], // Bond 2-11 (single)
  [2, 5], // Bond 3-6 (single)
  [2, 12], // Bond 3-13 (single)
  [4, 3], // Bond 5-4 (single)
  [3, 13], // Bond 4-14 (single)
  [4, 5], // Bond 5-6 (single)
  [4, 14], // Bond 5-15 (single)
  [5, 15], // Bond 6-16 (single)
  [7, 6], // Bond 8-7 (single)
  [10, 6], // Bond 11-7 (single)
  [6, 16], // Bond 7-17 (single)
  [8, 7], // Bond 9-8 (single)
  [7, 17], // Bond 8-18 (single)
  [9, 8], // Bond 10-9 (single)
  [8, 18], // Bond 9-19 (single)
  [9, 10], // Bond 10-11 (single)
  [9, 19], // Bond 10-20 (single)
  [10, 20], // Bond 11-21 (single)
];

export interface AtomPosition {
  x: number;
  y: number;
  z: number;
}

export const ATOM_POSITIONS: AtomPosition[] = [
  { x: -0.2061, y: 0.4051, z: 0.1670 },   // 0
  { x: 0.0000, y: 0.0000, z: 0.0001 },   // 1
  { x: -0.1912, y: 0.4112, z: -0.1695 },   // 2
  { x: 0.1083, y: 0.3765, z: 0.2846 },   // 3
  { x: 0.3175, y: 0.3651, z: 0.0208 },   // 4
  { x: 0.1324, y: 0.3865, z: -0.2598 },   // 5
  { x: 0.0863, y: -0.3928, z: -0.2695 },   // 6
  { x: -0.2427, y: -0.3671, z: -0.2018 },   // 7
  { x: -0.2807, y: -0.3714, z: 0.1329 },   // 8
  { x: 0.0247, y: -0.3998, z: 0.2720 },   // 9
  { x: 0.2515, y: -0.4131, z: 0.0233 },   // 10
  { x: -0.4186, y: 0.4173, z: 0.3081 },   // 11
  { x: -0.3904, y: 0.4288, z: -0.3283 },   // 12
  { x: 0.1759, y: 0.3632, z: 0.5305 },   // 13
  { x: 0.5715, y: 0.3417, z: 0.0317 },   // 14
  { x: 0.2216, y: 0.3822, z: -0.4990 },   // 15
  { x: 0.1919, y: -0.3939, z: -0.5020 },   // 16
  { x: -0.4301, y: -0.3454, z: -0.3738 },   // 17
  { x: -0.5020, y: -0.3537, z: 0.2590 },   // 18
  { x: 0.0756, y: -0.4076, z: 0.5221 },   // 19
  { x: 0.5046, y: -0.4324, z: 0.0518 },   // 20
];