// This file is auto-generated by the updateMoleculeConstants script
// Do not edit directly

export const MOLECULE_BONDS: [number, number][] = [
  [0, 3], // Bond 1-4 (single)
  [0, 10], // Bond 1-11 (single)
  [1, 5], // Bond 2-6 (single)
  [1, 11], // Bond 2-12 (single)
  [2, 5], // Bond 3-6 (double)
  [3, 4], // Bond 4-5 (single)
  [3, 5], // Bond 4-6 (single)
  [3, 6], // Bond 4-7 (single)
  [4, 7], // Bond 5-8 (single)
  [4, 8], // Bond 5-9 (single)
  [4, 9], // Bond 5-10 (single)
];

export interface AtomPosition {
  x: number;
  y: number;
  z: number;
}

export const ATOM_POSITIONS: AtomPosition[] = [
  { x: -0.2484, y: 0.3384, z: 0.0425 },   // 0
  { x: 0.4296, y: -0.1698, z: 0.0578 },   // 1
  { x: 0.3679, y: 0.3376, z: -0.1011 },   // 2
  { x: -0.0881, y: 0.0483, z: 0.0905 },   // 3
  { x: -0.2436, y: -0.1995, z: -0.1161 },   // 4
  { x: 0.2552, y: 0.0931, z: 0.0030 },   // 5
  { x: -0.1057, y: -0.0137, z: 0.3404 },   // 6
  { x: -0.2242, y: -0.1368, z: -0.3661 },   // 7
  { x: -0.4956, y: -0.2171, z: -0.0625 },   // 8
  { x: -0.1358, y: -0.4316, z: -0.0833 },   // 9
  { x: -0.1633, y: 0.4898, z: 0.1922 },   // 10
  { x: 0.6521, y: -0.1387, z: 0.0027 },   // 11
];