// This file is auto-generated by the updateMoleculeConstants script
// Do not edit directly

export const MOLECULE_BONDS: [number, number][] = [
  [0, 1], // Bond 1-2 (single)
  [1, 2], // Bond 2-3 (single)
  [1, 3], // Bond 2-4 (single)
  [1, 4], // Bond 2-5 (single)
  [4, 5], // Bond 5-6 (single)
];

export interface AtomPosition {
  x: number;
  y: number;
  z: number;
}

export const ATOM_POSITIONS: AtomPosition[] = [
  { x: 0.0340, y: -0.4633, z: -0.1572 },   // 0
  { x: 0.0280, y: -0.0194, z: -0.1548 },   // 1
  { x: 0.4445, y: 0.1342, z: -0.1579 },   // 2
  { x: -0.1867, y: 0.1276, z: -0.5144 },   // 3
  { x: -0.2444, y: 0.1683, z: 0.3240 },   // 4
  { x: -0.0753, y: 0.0525, z: 0.6603 },   // 5
];