// This file is auto-generated by the updateMoleculeConstants script
// Do not edit directly

export const MOLECULE_BONDS: [number, number][] = [
  [0, 8], // Bond 1-9 (double)
  [1, 10], // Bond 2-11 (double)
  [2, 12], // Bond 3-13 (single)
  [2, 23], // Bond 3-24 (single)
  [3, 12], // Bond 4-13 (double)
  [4, 7], // Bond 5-8 (single)
  [4, 10], // Bond 5-11 (single)
  [4, 15], // Bond 5-16 (single)
  [5, 8], // Bond 6-9 (single)
  [5, 9], // Bond 6-10 (single)
  [5, 16], // Bond 6-17 (single)
  [6, 11], // Bond 7-12 (single)
  [6, 21], // Bond 7-22 (single)
  [6, 22], // Bond 7-23 (single)
  [7, 8], // Bond 8-9 (single)
  [7, 13], // Bond 8-14 (single)
  [7, 14], // Bond 8-15 (single)
  [9, 12], // Bond 10-13 (single)
  [9, 17], // Bond 10-18 (single)
  [9, 18], // Bond 10-19 (single)
  [10, 11], // Bond 11-12 (single)
  [11, 19], // Bond 12-20 (single)
  [11, 20], // Bond 12-21 (single)
];

export interface AtomPosition {
  x: number;
  y: number;
  z: number;
}

export const ATOM_POSITIONS: AtomPosition[] = [
  { x: -0.1246, y: 0.1474, z: 0.1929 },   // 0
  { x: 0.2193, y: -0.1627, z: -0.1051 },   // 1
  { x: -0.3444, y: -0.2333, z: -0.0283 },   // 2
  { x: -0.6332, y: -0.1920, z: 0.0811 },   // 3
  { x: 0.2032, y: 0.1349, z: 0.0084 },   // 4
  { x: -0.2801, y: 0.1153, z: -0.0838 },   // 5
  { x: 0.5688, y: -0.1959, z: 0.0324 },   // 6
  { x: 0.0411, y: 0.1921, z: -0.0910 },   // 7
  { x: -0.1266, y: 0.1487, z: 0.0241 },   // 8
  { x: -0.4592, y: 0.0743, z: -0.0086 },   // 9
  { x: 0.2793, y: -0.0390, z: -0.0071 },   // 10
  { x: 0.4456, y: -0.0622, z: 0.1157 },   // 11
  { x: -0.4901, y: -0.1284, z: 0.0199 },   // 12
  { x: 0.0487, y: 0.3405, z: -0.1128 },   // 13
  { x: 0.0360, y: 0.1215, z: -0.2235 },   // 14
  { x: 0.2604, y: 0.2268, z: 0.0964 },   // 15
  { x: -0.2679, y: 0.1187, z: -0.2227 },   // 16
  { x: -0.5612, y: 0.1252, z: -0.1064 },   // 17
  { x: -0.4744, y: 0.1441, z: 0.1235 },   // 18
  { x: 0.3998, y: -0.1101, z: 0.2505 },   // 19
  { x: 0.5180, y: 0.0683, z: 0.1333 },   // 20
  { x: 0.6074, y: -0.1523, z: -0.0949 },   // 21
  { x: 0.5020, y: -0.3175, z: 0.0143 },   // 22
  { x: -0.3679, y: -0.3644, z: -0.0084 },   // 23
];