// This file is auto-generated by the updateMoleculeConstants script
// Do not edit directly

export const MOLECULE_BONDS: [number, number][] = [
  [0, 1], // Bond 1-2 (single)
  [0, 4], // Bond 1-5 (single)
  [0, 8], // Bond 1-9 (single)
  [0, 10], // Bond 1-11 (single)
  [1, 5], // Bond 2-6 (single)
  [1, 6], // Bond 2-7 (single)
  [1, 11], // Bond 2-12 (single)
  [2, 3], // Bond 3-4 (single)
  [2, 4], // Bond 3-5 (single)
  [2, 7], // Bond 3-8 (single)
  [2, 12], // Bond 3-13 (single)
  [3, 5], // Bond 4-6 (single)
  [3, 9], // Bond 4-10 (single)
  [3, 13], // Bond 4-14 (single)
  [4, 14], // Bond 5-15 (single)
  [4, 15], // Bond 5-16 (single)
  [5, 16], // Bond 6-17 (single)
  [5, 17], // Bond 6-18 (single)
  [6, 7], // Bond 7-8 (single)
  [6, 18], // Bond 7-19 (single)
  [6, 19], // Bond 7-20 (single)
  [7, 20], // Bond 8-21 (single)
  [7, 21], // Bond 8-22 (single)
  [8, 9], // Bond 9-10 (single)
  [8, 22], // Bond 9-23 (single)
  [8, 23], // Bond 9-24 (single)
  [9, 24], // Bond 10-25 (single)
  [9, 25], // Bond 10-26 (single)
];

export interface AtomPosition {
  x: number;
  y: number;
  z: number;
}

export const ATOM_POSITIONS: AtomPosition[] = [
  { x: 0.1064, y: 0.2549, z: -0.1442 },   // 0
  { x: -0.1064, y: 0.2550, z: 0.1441 },   // 1
  { x: -0.1064, y: -0.2550, z: -0.1441 },   // 2
  { x: 0.1064, y: -0.2549, z: 0.1442 },   // 3
  { x: 0.0000, y: -0.0000, z: -0.3582 },   // 4
  { x: 0.0000, y: 0.0001, z: 0.3582 },   // 5
  { x: -0.4327, y: 0.1673, z: 0.0524 },   // 6
  { x: -0.4327, y: -0.1673, z: -0.0524 },   // 7
  { x: 0.4327, y: 0.1673, z: -0.0525 },   // 8
  { x: 0.4327, y: -0.1673, z: 0.0525 },   // 9
  { x: 0.1015, y: 0.4749, z: -0.2585 },   // 10
  { x: -0.1016, y: 0.4749, z: 0.2583 },   // 11
  { x: -0.1015, y: -0.4749, z: -0.2583 },   // 12
  { x: 0.1016, y: -0.4749, z: 0.2585 },   // 13
  { x: 0.1829, y: -0.0773, z: -0.5075 },   // 14
  { x: -0.1829, y: 0.0772, z: -0.5075 },   // 15
  { x: 0.1829, y: 0.0774, z: 0.5075 },   // 16
  { x: -0.1829, y: -0.0772, z: 0.5075 },   // 17
  { x: -0.5894, y: 0.1948, z: 0.2430 },   // 18
  { x: -0.5133, y: 0.3159, z: -0.1295 },   // 19
  { x: -0.5894, y: -0.1949, z: -0.2430 },   // 20
  { x: -0.5132, y: -0.3160, z: 0.1295 },   // 21
  { x: 0.5132, y: 0.3160, z: 0.1293 },   // 22
  { x: 0.5894, y: 0.1948, z: -0.2431 },   // 23
  { x: 0.5132, y: -0.3160, z: -0.1294 },   // 24
  { x: 0.5894, y: -0.1948, z: 0.2431 },   // 25
];